apiVersion : apps/v1
kind: Deployment
metadata:
  name: "actionsdemoaks-e87f"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "actionsdemoaks-e87f"
  template:
    metadata:
      labels:
        app: "actionsdemoaks-e87f"
    spec:
      containers:
        - name: "actionsdemoaks-e87f"
          image: "83b69b7c9fe140929c704942f935c92f.azurecr.io/actionsdemoaks"
          ports:
          - containerPort: 8080