apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akskodey-60d8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akskodey-60d8"
  template:
    metadata:
      labels:
        app: "akskodey-60d8"
    spec:
      containers:
        - name: "akskodey-60d8"
          image: "absfsf.azurecr.io/akskodey"
          ports:
          - containerPort: 8080