apiVersion: v1
kind: Service
metadata:
    name: "akskodey-60d8"
    labels:
        app: "akskodey-60d8"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "akskodey-60d8"