on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: absfsf.azurecr.io
        username: ${{ secrets.acr_absfsf_username }}
        password: ${{ secrets.acr_absfsf_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/bulletin-board-app" -f  "bulletin-board-app/Dockerfile" -t absfsf.azurecr.io/akskodey:${{ github.sha }}
        docker push absfsf.azurecr.io/akskodey:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akskodey_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akskodeyd523 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akskodeyd523`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akskodeyd523
        container-registry-url: absfsf.azurecr.io
        container-registry-username: ${{ secrets.acr_absfsf_username }}
        container-registry-password: ${{ secrets.acr_absfsf_password }}
        secret-name: akskodeydockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: akskodeyd523
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          absfsf.azurecr.io/akskodey:${{ github.sha }}
        imagepullsecrets: |
          akskodeydockerauth