on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrd62kd5oifovc2.azurecr.io
        username: ${{ secrets.acr_acrd62kd5oifovc2_username }}
        password: ${{ secrets.acr_acrd62kd5oifovc2_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/bulletin-board-app" -f  "bulletin-board-app/Dockerfile" -t acrd62kd5oifovc2.azurecr.io/azuretriggeraks:${{ github.sha }}
        docker push acrd62kd5oifovc2.azurecr.io/azuretriggeraks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_azuretriggeraks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azuretriggeraks5600 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azuretriggeraks5600`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azuretriggeraks5600
        container-registry-url: acrd62kd5oifovc2.azurecr.io
        container-registry-username: ${{ secrets.acr_acrd62kd5oifovc2_username }}
        container-registry-password: ${{ secrets.acr_acrd62kd5oifovc2_password }}
        secret-name: azuretriggerdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace : azuretriggeraks5600
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acrd62kd5oifovc2.azurecr.io/azuretriggeraks:${{ github.sha }}
        imagepullsecrets: |
          azuretriggerdockerauth
